// These files land in the user's own repository, so the case that matters most
// is the one where Docket must NOT write: a charter or manifest a person edited
// by hand.
import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url, { interopDefault: true });
const { anthropic } = jiti("../src/shared/agent-model.ts");
const { writeAgentFiles } = jiti(fileURLToPath(new URL("../src/main/agent-files.ts", import.meta.url)));

const workspace = () => mkdtemp(join(tmpdir(), "docket-agents-"));

test("writes a subagent file per agent plus the manifest", async () => {
  const root = await workspace();
  const result = await writeAgentFiles(root, ["lead", "engineer"], {});

  assert.deepEqual(
    [...result.written].sort(),
    ["AGENTS.md", ".claude/agents/engineer.md", ".claude/agents/lead.md"].sort(),
  );
  assert.deepEqual([...result.skipped], []);

  const lead = await readFile(join(root, ".claude/agents/lead.md"), "utf8");
  assert.ok(lead.startsWith("---\n"), "must open with frontmatter");
  assert.match(lead, /^name: lead$/m);
  assert.ok(lead.includes("You are the Lead"));
});

test("the marker sits outside the frontmatter block", async () => {
  const root = await workspace();
  await writeAgentFiles(root, ["lead"], {});
  const file = await readFile(join(root, ".claude/agents/lead.md"), "utf8");

  // An unrecognized key inside frontmatter would be carried into the loaded
  // definition, so the marker has to live below the closing fence.
  const frontmatter = /^---\n([\s\S]*?)\n---\n/.exec(file)[1];
  assert.ok(!frontmatter.includes("generated by Docket"));
  assert.ok(file.includes("<!-- generated by Docket"));
});

test("a hand-written charter is never overwritten", async () => {
  const root = await workspace();
  await mkdir(join(root, ".claude/agents"), { recursive: true });
  const mine = "---\nname: lead\ndescription: my own\n---\n\nMy rules.\n";
  await writeFile(join(root, ".claude/agents/lead.md"), mine);

  const result = await writeAgentFiles(root, ["lead", "engineer"], {});

  assert.deepEqual([...result.skipped], [".claude/agents/lead.md"]);
  assert.equal(await readFile(join(root, ".claude/agents/lead.md"), "utf8"), mine);
  assert.ok(result.written.includes(".claude/agents/engineer.md"), "others still write");
});

test("a hand-written AGENTS.md is never overwritten", async () => {
  const root = await workspace();
  await writeFile(join(root, "AGENTS.md"), "# Our conventions\n\nRun make test.\n");

  const result = await writeAgentFiles(root, ["lead"], {});

  assert.ok(result.skipped.includes("AGENTS.md"));
  assert.match(await readFile(join(root, "AGENTS.md"), "utf8"), /Our conventions/);
});

test("a file Docket generated earlier is refreshed in place", async () => {
  const root = await workspace();
  await writeAgentFiles(root, ["lead"], {});
  const second = await writeAgentFiles(root, ["lead"], { lead: anthropic("haiku") });

  assert.ok(second.written.includes(".claude/agents/lead.md"));
  assert.deepEqual([...second.skipped], []);
  assert.match(await readFile(join(root, ".claude/agents/lead.md"), "utf8"), /^model: haiku$/m);
});

test("the chosen model reaches the file, and the default fills the rest", async () => {
  const root = await workspace();
  await writeAgentFiles(root, ["lead", "docs"], { lead: anthropic("sonnet") });

  assert.match(await readFile(join(root, ".claude/agents/lead.md"), "utf8"), /^model: sonnet$/m);
  // docs defaults to haiku and was not overridden.
  assert.match(await readFile(join(root, ".claude/agents/docs.md"), "utf8"), /^model: haiku$/m);
});

test("only the agents on the team are written", async () => {
  const root = await workspace();
  const result = await writeAgentFiles(root, ["lead"], {});
  assert.ok(!result.written.some((path) => path.includes("security")));
  await assert.rejects(() => readFile(join(root, ".claude/agents/security.md"), "utf8"));
});
