/**
 * Writes the team to disk in the formats the underlying CLIs actually read.
 *
 * Two formats, because the two providers Docket drives disagree:
 *
 *   .claude/agents/<handle>.md   Claude Code subagent definitions, one file per
 *                                agent, YAML frontmatter plus the charter.
 *   AGENTS.md                    The open format Codex and most other agents
 *                                read. One file, plain prose, no schema.
 *
 * These files land in the user's repository, so the rule is that Docket owns
 * what it generated and nothing else. Generated files carry a marker; a file
 * without one was written by a person and is never overwritten.
 */
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  type AgentDefinition,
  type AgentId,
  type AgentModel,
  agent,
  renderAgentFile,
  renderAgentsManifest,
} from "../shared/agent-roster";

/** Present in every generated file. Its absence means a human owns the file. */
const MARKER = "generated by Docket";

export type WriteResult = Readonly<{
  written: readonly string[];
  /** Files left alone because a person wrote them. */
  skipped: readonly string[];
}>;

export async function writeAgentFiles(
  workspacePath: string,
  team: readonly AgentId[],
  models: Readonly<Partial<Record<AgentId, AgentModel>>>,
): Promise<WriteResult> {
  const definitions = team.map((id) => agent(id));
  const written: string[] = [];
  const skipped: string[] = [];

  const agentsDirectory = join(workspacePath, ".claude", "agents");
  await mkdir(agentsDirectory, { recursive: true });

  for (const definition of definitions) {
    const relative = `.claude/agents/${definition.handle}.md`;
    const target = join(agentsDirectory, `${definition.handle}.md`);
    if (await isHumanOwned(target)) {
      skipped.push(relative);
      continue;
    }
    await writeAtomic(target, withMarker(definition, renderAgentFile(definition, modelFor(definition, models))));
    written.push(relative);
  }

  const manifestPath = join(workspacePath, "AGENTS.md");
  if (await isHumanOwned(manifestPath)) {
    skipped.push("AGENTS.md");
  } else {
    await writeAtomic(manifestPath, renderAgentsManifest(definitions, models));
    written.push("AGENTS.md");
  }

  return Object.freeze({ written: Object.freeze(written), skipped: Object.freeze(skipped) });
}

function modelFor(
  definition: AgentDefinition,
  models: Readonly<Partial<Record<AgentId, AgentModel>>>,
): AgentModel {
  return models[definition.id] ?? definition.defaultModel;
}

/**
 * The marker goes in an HTML comment under the frontmatter rather than inside
 * it: an unrecognized frontmatter key would be carried into the loaded
 * definition, and a comment is invisible to the agent reading its own charter.
 */
function withMarker(definition: AgentDefinition, file: string): string {
  const end = file.indexOf("\n---\n", 4);
  const head = file.slice(0, end + 5);
  const body = file.slice(end + 5);
  return `${head}\n<!-- ${MARKER}. Edit this agent in Docket; changes here are replaced. -->\n${body}`;
}

async function isHumanOwned(path: string): Promise<boolean> {
  try {
    return !(await readFile(path, "utf8")).includes(MARKER);
  } catch (error) {
    // Absent is not human-owned; anything else unreadable is treated as owned,
    // because overwriting a file we could not inspect is the worse mistake.
    return (error as NodeJS.ErrnoException).code !== "ENOENT";
  }
}

async function writeAtomic(path: string, contents: string): Promise<void> {
  const temporary = `${path}.tmp`;
  await writeFile(temporary, contents, "utf8");
  await rename(temporary, path);
}
